lang: en-US

title: Waypoint Spine
description: Waypoint Spine is an orthopedic practice dedicated exclusively to the evaluation and treatment of disorders of the cervical, thoracic, and lumbar spine.
url: https://waypointspine.com
timezone: America/Chicago

permalink: pretty

exclude: ['Gemfile', 'Gemfile.lock', 'CNAME', 'locations.html', 'team.html', 'about.html', 'praise.html', 'locations', 'team', 'map.html']
