lang: en-US

title: Waypoint Spine
description: Waypoint Spine is an orthopedic practice dedicated exclusively to the evaluation and treatment of disorders of the cervical, thoracic, and lumbar spine.
url: https://waypointspine.com
timezone: America/Chicago

permalink: pretty

exclude: ['Gemfile', 'Gemfile.lock', 'CNAME', 'about.html', 'consult.html', 'covid19.html', 'locations', 'locations.html', 'map.html', 'MRI.html', 'O-Arm.html', 'offline.html', 'si-joint.html', 'team', 'team.html', 'reviews.html']
